spring.application.name=LearnSphere
# ===============================
# Server Configuration
# ===============================
server.port=${PORT:8080}

# ===============================
# PostgreSQL Database Configuration
# ===============================
spring.datasource.url=${DATABASE_URL:jdbc:postgresql://localhost:5432/learnsphere_db}
spring.datasource.username=${DATABASE_USER:postgres}
spring.datasource.password=${DATABASE_PASS:root}

# ===============================
# CORS Configuration
# ===============================
cors.allowed-origins=${CORS_ALLOWED_ORIGINS:http://localhost:4200,http://localhost:3000}

spring.datasource.driver-class-name=org.postgresql.Driver

# ===============================
# JPA / Hibernate Configuration
# ===============================
spring.jpa.hibernate.ddl-auto=update

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# ===============================
# Hibernate Performance
# ===============================
spring.jpa.open-in-view=false
